[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server-hybrid.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { value = "3000" }
DB_SSL = { value = "true" }
DB_SSL_REJECT_UNAUTHORIZED = { value = "false" }
